In [2]:
# creating numpy/n-d array

import numpy as np

In [3]:
arr1 = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [4]:
type(arr1)

numpy.ndarray

In [5]:
arr2 = np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
arr3 = np.zeros((2,3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [7]:
arr4 = np.ones((3,3))
arr4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [9]:
arr5 = np.identity(5)
arr5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [11]:
arr6 = np.arange(10)
arr6

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
arr7 = np.arange(2,10,2)
arr7

array([2, 4, 6, 8])

In [13]:
arr8 = np.linspace(10,20,10)
arr8

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [14]:
arr9 = arr8.copy()
arr9

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [15]:
arr1.shape

(5,)

In [16]:
arr2.shape

(2, 3)

In [19]:
arr10 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
arr10

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [20]:
arr10.shape

(2, 2, 2)

In [21]:
 arr10.ndim

3

In [22]:
arr1.ndim

1

In [23]:
arr2.ndim

2

In [24]:
arr1.size

5

In [25]:
arr9.size

10

In [28]:
arr9.itemsize

8

In [27]:
arr8.itemsize

8

In [29]:
arr8.dtype

dtype('float64')

In [30]:
arr10.dtype

dtype('int64')

In [31]:
arr10.astype('float')

array([[[1., 2.],
        [3., 4.]],

       [[5., 6.],
        [7., 8.]]])

In [32]:
lista = range(100)
arr11 = np.arange(100)

In [33]:
import sys

In [34]:
print(sys.getsizeof(87)*len(lista))

2800


In [35]:
print(arr11.itemsize*arr11.size)

800


In [36]:
import time

In [39]:
x = range(1000000)
y = range(1000000,2000000)

start_time = time.time()

c = [x+y for x,y in zip(x,y)]

print(time.time()-start_time)

0.047940969467163086


In [40]:
a = np.arange(1000000)
b = np.arange(1000000,2000000)
start_time =  time.time()
c=a+b

print(time.time()-start_time)

0.001840829849243164


In [41]:
arr12 = np.arange(24)
arr12

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [46]:
arr12 = arr12.reshape(6,4)
arr12

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [47]:
arr12[2]

array([ 8,  9, 10, 11])

In [51]:
arr12[:,2]

array([ 2,  6, 10, 14, 18, 22])

In [53]:
arr12[:,1:3]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14],
       [17, 18],
       [21, 22]])

In [54]:
arr12[2:4,1:3]

array([[ 9, 10],
       [13, 14]])

In [55]:
arr12[4:,2:]

array([[18, 19],
       [22, 23]])

In [56]:
arr12

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [57]:
for i in arr12:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[16 17 18 19]
[20 21 22 23]


In [58]:
for i in np.nditer(arr12):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
